# Ashva Production Strategies Module
from src.strategies.base import BaseStrategy
from src.strategies.alpha_trend_surfer import AlphaTrendSurfer
from src.strategies.alpha_orb_pro import AlphaAuctionORBPro
from src.strategies.alpha_03_vwap_reversion import Alpha03VWAPReversion
from src.strategies.alpha_04_gap_and_go import Alpha04GapAndGo
from src.strategies.alpha_71_outlier_volume_drive import Alpha71OutlierVolumeDrive
from src.strategies.alpha_72_nr3_volatility_expansion import Alpha72NR3VolatilityExpansion
from src.strategies.alpha_73_inside_day_expansion import Alpha73InsideDayExpansion
from src.strategies.alpha_74_gap_marubozu_momentum import Alpha74GapMarubozuMomentum
from src.strategies.alpha_75_morning_drive_continuation import Alpha75MorningDriveContinuation
from src.strategies.alpha_76_two_day_momentum_gap_surge import Alpha76TwoDayMomentumGapSurge
from src.strategies.alpha_77_nr4_shock_expansion import Alpha77NR4ShockExpansion
from src.strategies.alpha_78_double_inside_momentum import Alpha78DoubleInsideMomentum
from src.strategies.alpha_79_high_rr_opening_drive import Alpha79HighRROpeningDrive
from src.strategies.alpha_80_nr7_volatility_expansion import Alpha80NR7VolatilityExpansion
